#!/bin/bash

ENV_PATH="testenv"

python -V
python3 -V

# create virtual environment
# python -m venv $ENV_PATH
# source $ENV_PATH/bin/activate

# install relevant tools in virtual environment
pip install -U pytest pytest-cov

# run tests
pytest --cov=projects/fizzbuzz/python/combined/ --cov-report=term-missing projects/fizzbuzz/python/combined/fizzbuzz_test.py

# remove latent files
rm -rf $ENV_PATH
rm .coverage