openapi: 3.0.0
info:
  title: Project5_FizzBuzz++
  description: creating a microservice to test fizzbuzz
  version: 1.0.0
paths:
  /fizzbuzz:
    get:
      summary: print the fizzbuzz output
      parameters:
        - name: num
          in: query
          required: true
          schema:
            type: integer
          description: "the number we pass to fizzbuzz"
      responses:
        '200':
          description: JSON output
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
